"""Prometheus Telemetry & Instrumentation Module.

Exports production metrics matching specifications in docs/OBSERVABILITY.md.
"""

from contextlib import contextmanager
import time
from typing import Generator
from prometheus_client import Counter, Histogram, Gauge

# Counters
TRANSACTIONS_PROCESSED = Counter(
    "transactions_processed_total",
    "Cumulative count of transactions processed by the pipeline",
    ["status"],  # success, error, duplicate
)

PREDICTIONS_COUNT = Counter(
    "fraud_predictions_total",
    "Total inferences generated by machine learning models",
    ["model_version", "model_type"],
)

DECISIONS_COUNT = Counter(
    "transactions_decision_total",
    "Total transactions triaged by risk engine",
    ["decision", "policy_version"],  # APPROVE, REVIEW, BLOCK
)

API_ERRORS_TOTAL = Counter(
    "api_errors_total",
    "Total HTTP API error responses",
    ["endpoint", "error_type"],
)

# Histograms
PREDICTION_LATENCY = Histogram(
    "prediction_latency_seconds",
    "Latency breakdown across pipeline stages in seconds",
    ["step"],  # features, inference, shap, risk
    buckets=(0.001, 0.005, 0.010, 0.025, 0.050, 0.100, 0.250, 0.500),
)

API_REQUEST_LATENCY = Histogram(
    "api_request_latency_seconds",
    "HTTP REST endpoint latency in seconds",
    ["method", "endpoint", "status_code"],
    buckets=(0.005, 0.010, 0.025, 0.050, 0.100, 0.250, 0.500, 1.000),
)

CALIBRATED_PROB_HIST = Histogram(
    "calibrated_probability_distribution",
    "Empirical distribution of emitted calibrated fraud probabilities",
    ["model_version"],
    buckets=(0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00),
)

RISK_SCORE_HIST = Histogram(
    "risk_score_distribution",
    "Histogram of composite 0-100 risk scores",
    ["policy_version"],
    buckets=(10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0),
)

# Gauges
KAFKA_CONSUMER_LAG = Gauge(
    "kafka_consumer_lag",
    "Unconsumed message backlog per partition",
    ["topic", "consumer_group", "partition"],
)


@contextmanager
def track_stage_latency(step: str) -> Generator[None, None, None]:
    """Context manager recording high-resolution stage latency into Prometheus."""
    start = time.perf_counter()
    try:
        yield
    finally:
        elapsed = time.perf_counter() - start
        PREDICTION_LATENCY.labels(step=step).observe(elapsed)


def record_transaction_metric(decision: str, score: float, prob: float, model_version: str = "v1.0.0"):
    """Records consolidated telemetry for an evaluated transaction."""
    TRANSACTIONS_PROCESSED.labels(status="success").inc()
    DECISIONS_COUNT.labels(decision=decision, policy_version="v1.0.0").inc()
    PREDICTIONS_COUNT.labels(model_version=model_version, model_type="xgboost").inc()
    CALIBRATED_PROB_HIST.labels(model_version=model_version).observe(prob)
    RISK_SCORE_HIST.labels(policy_version="v1.0.0").observe(score)
